{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "db446cac-3cb1-4347-b149-e722646a80a9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "$ python projekt1.py\n",
      "username: bob\n",
      "password: 123\n",
      "----------------------------------------\n",
      "Welcome to the app, bob\n",
      "We have 3 texts to be analyzed.\n",
      "Login succesful\n",
      "----------------------------------------\n",
      "Enter a number btw. 1 and 3 to select:  [1]\n",
      "----------------------------------------\n",
      "There are 54 words in the selected text\n",
      "There are 12 titlecase words.\n",
      "There are 1 uppercase words.\n",
      "There are 38 lowercase words.\n",
      "There are 3 numeric strings.\n",
      "The sum of all the numbers 8510 .\n",
      "----------------------------------------\n",
      "LEN|  OCCURENCES  |NR.\n",
      "----------------------------------------\n",
      "  1|*             |1\n",
      "  2|*********     |9\n",
      "  3|******        |6\n",
      "  4|***********   |11\n",
      "  5|***********   |11\n",
      "  6|***           |3\n",
      "  7|*****         |5\n",
      "  8|***           |3\n",
      "  9|***           |3\n",
      " 10|*             |1\n",
      " 11|*             |1\n"
     ]
    }
   ],
   "source": [
    "\n",
    "\n",
    "\n",
    "\n",
    "def login():\n",
    "\n",
    "\n",
    "      '''\n",
    "      author = Barbora Kauerova\n",
    "      discord = barborakauerova_12439\n",
    "      email = kauerova.barbora.bk@gmail.com\n",
    "      '''\n",
    "      TEXTS = ['''\n",
    "      Situated about 10 miles west of Kemmerer,\n",
    "      Fossil Butte is a ruggedly impressive\n",
    "      topographic feature that rises sharply\n",
    "      some 1000 feet above Twin Creek Valley\n",
    "      to an elevation of more than 7500 feet\n",
    "      above sea level. The butte is located just\n",
    "      north of US 30N and the Union Pacific Railroad,\n",
    "      which traverse the valley. ''',\n",
    "      '''At the base of Fossil Butte are the bright\n",
    "      red, purple, yellow and gray beds of the Wasatch\n",
    "      Formation. Eroded portions of these horizontal\n",
    "      beds slope gradually upward from the valley floor\n",
    "      and steepen abruptly. Overlying them and extending\n",
    "      to the top of the butte are the much steeper\n",
    "      buff-to-white beds of the Green River Formation,\n",
    "      which are about 300 feet thick.''',\n",
    "      '''The monument contains 8198 acres and protects\n",
    "      a portion of the largest deposit of freshwater fish\n",
    "      fossils in the world. The richest fossil fish deposits\n",
    "      are found in multiple limestone layers, which lie some\n",
    "      100 feet below the top of the butte. The fossils\n",
    "      represent several varieties of perch, as well as\n",
    "      other freshwater genera and herring similar to those\n",
    "      in modern oceans. Other fish such as paddlefish,\n",
    "      garpike and stingray are also present.''']\n",
    "\n",
    "\n",
    "      #Přihlásím se pomocí jména a hesla\n",
    "      users={\"bob\":\"123\",\"ann\":\"pass123\",\"mike\":\"password123\",\"liz\":\"pass123\"}\n",
    "\n",
    "      username=input(\"Enter your username: \")\n",
    "      password=input(\"Enter your password: \")\n",
    "      print(\"$ python projekt1.py\")\n",
    "      print(\"username:\",username)\n",
    "      print(\"password:\",password)\n",
    "      print(\"----------------------------------------\")\n",
    "\n",
    "      #Pokud je přihlášení správné, vyberu si číslo odstavce\n",
    "      if username in users and users[username] == password:\n",
    "            print(\"Welcome to the app,\",username)\n",
    "            print(\"We have 3 texts to be analyzed.\")\n",
    "            print(\"Login succesful\")\n",
    "            print(\"----------------------------------------\")\n",
    "            number=input(\"Enter a number btw. 1 and 3 to select: \")\n",
    "            print(\"Enter a number btw. 1 and 3 to select: \",[int(number)])\n",
    "            print(\"----------------------------------------\")\n",
    "      else:\n",
    "            print(\"unregistered user, terminating the program..\")\n",
    "\n",
    "      #Celkový počet slov v odstavci\n",
    "      pocet_slov=TEXTS[int(number)-1].split()\n",
    "      print(\"There are\",len(pocet_slov),\"words in the selected text\")\n",
    "\n",
    "      \n",
    "      uppercase=0\n",
    "      lowercase=0\n",
    "      titlecase=0\n",
    "      numeric=0\n",
    "      total_sum=0\n",
    "\n",
    "            #Počet velkých písmen ve slově \n",
    "      for L in TEXTS[int(number)-1].split():\n",
    "            if(L.isupper() and not(L.isalpha())):\n",
    "                  uppercase=uppercase+1\n",
    "            #Počet malých písmen ve slově      \n",
    "            elif(L.islower()):\n",
    "                  lowercase=lowercase+1\n",
    "            #Počet prvních velkých písmen ve slově\n",
    "            elif(L.istitle() or not (L.isnumeric())):\n",
    "                  titlecase=titlecase+1\n",
    "            #Součet čísel \n",
    "            elif(L.isnumeric()):\n",
    "                  numeric=numeric+1\n",
    "      for S in TEXTS[int(number)-1].split():\n",
    "            if isinstance(S, int) or (hasattr(S,'isdigit') and S.isdigit()):\n",
    "                  total_sum=total_sum+int(S)\n",
    "\n",
    "      \n",
    "\n",
    "\n",
    "      print(\"There are\",titlecase,\"titlecase words.\")\n",
    "      print(\"There are\",uppercase,\"uppercase words.\")\n",
    "      print(\"There are\",lowercase,\"lowercase words.\")\n",
    "      print(\"There are\",numeric,\"numeric strings.\")\n",
    "      print(\"The sum of all the numbers\",total_sum,\".\")\n",
    "      print(\"----------------------------------------\")\n",
    "      \n",
    "\n",
    "      #sorted_data = sorted(TEXTS[int(number)-1].split(), key=len)\n",
    "      #print(sorted_data)\n",
    "      analyze_and_print_word_lengths(TEXTS[int(number)-1])\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "def analyze_and_print_word_lengths(text):\n",
    "    # Rozdělíme text na slova\n",
    "    words = text.split()\n",
    "    word_lengths = [len(word) for word in words]\n",
    "\n",
    "    # Získáme počet výskytů každé délky\n",
    "    length_counts = {}\n",
    "    for length in word_lengths:\n",
    "        if length in length_counts:\n",
    "            length_counts[length] += 1\n",
    "        else:\n",
    "            length_counts[length] = 1\n",
    "\n",
    "    # Vytiskneme tabulku\n",
    "    print(\"LEN|  OCCURENCES  |NR.\")\n",
    "    print(\"----------------------------------------\")\n",
    "    for length, count in sorted(length_counts.items()):\n",
    "        print(f\"{length:3}|{'*' * count:<14}|{count}\")\n",
    "\n",
    "login()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
